const mongoose = require('mongoose');
const uniqueValidator = require('mongoose-unique-validator');

const userSchema = mongoose.Schema({
  email: { type: String, required: true, unique: true },
  password: { type: String, required: true},
  username: { type: String, required: true, unique: true },
  character: { type: String, required: true },
  boulder: { type: Boolean },
  cascade: { type: Boolean },
  thunder: { type: Boolean },
  rainbow: { type: Boolean },
  soul: { type: Boolean },
  marsh: { type: Boolean },
  volcano: { type: Boolean },
  earth: { type: Boolean },
  zephyr: { type: Boolean },
  hive: { type: Boolean },
  plain: { type: Boolean },
  fog: { type: Boolean },
  storm: { type: Boolean },
  mineral: { type: Boolean },
  glacier: { type: Boolean },
  rising: { type: Boolean },
  stone: { type: Boolean },
  knuckle: { type: Boolean },
  dynamo: { type: Boolean },
  heat: { type: Boolean },
  balance: { type: Boolean },
  feather: { type: Boolean },
  mind: { type: Boolean },
  rain: { type: Boolean },
  coal: { type: Boolean },
  forest: { type: Boolean },
  cobble: { type: Boolean },
  fen: { type: Boolean },
  relic: { type: Boolean },
  mine: { type: Boolean },
  icicle: { type: Boolean },
  beacon: { type: Boolean },
  trio: { type: Boolean },
  basic: { type: Boolean },
  insect: { type: Boolean },
  bolt: { type: Boolean },
  quake: { type: Boolean },
  jet: { type: Boolean },
  freeze: { type: Boolean },
  legend: { type: Boolean },
  toxic: { type: Boolean },
  wave: { type: Boolean },
  bug: { type: Boolean },
  cliff: { type: Boolean },
  rumble: { type: Boolean },
  plant: { type: Boolean },
  voltage: { type: Boolean },
  fairy: { type: Boolean },
  psychic: { type: Boolean },
  iceberg: { type: Boolean },
  grass: { type: Boolean },
  water: { type: Boolean },
  fire: { type: Boolean },
  fighting: { type: Boolean },
  fairy: { type: Boolean },
  rock: { type: Boolean },
  dark: { type: Boolean },
  dragon: { type: Boolean },
  ghost: { type: Boolean },
  ice: { type: Boolean },
});

userSchema.plugin(uniqueValidator);

module.exports = mongoose.model('User', userSchema);
